# Generated by Django 4.0.3 on 2022-05-21 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notificacoes', '0003_notificacaorestaurante'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
