# Generated by Django 4.0.3 on 2022-04-27 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estatistica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuncNotficaEnv',
            fields=[
                ('funcionarioid', models.OneToOneField(db_column='FuncionarioID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='estatistica.funcionario')),
            ],
            options={
                'db_table': 'func_notfica_env',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FuncNotificaRec',
            fields=[
                ('funcionarioid', models.OneToOneField(db_column='FuncionarioID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='estatistica.funcionario')),
            ],
            options={
                'db_table': 'func_notifica_rec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='NotificacaoRestaurante',
            fields=[
                ('notificacaoid', models.OneToOneField(db_column='NotificacaoID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='estatistica.notificacao')),
            ],
            options={
                'db_table': 'notificacao_restaurante',
                'managed': False,
            },
        ),
    ]
