# Generated by Django 4.0.3 on 2022-04-30 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0002_funcnotficaenv_funcnotificarec_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=40, null=True)),
                ('numerotelefone', models.IntegerField(db_column='NumeroTelefone')),
                ('email', models.CharField(blank=True, db_column='Email', max_length=100, null=True)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=30, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FuncionarioNotificacao',
            fields=[
                ('notificacaoid', models.OneToOneField(db_column='NotificacaoID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='restaurantes.notificacao')),
                ('funcionarioid_recetor', models.IntegerField()),
                ('visto', models.IntegerField(blank=True, null=True)),
                ('data', models.DateTimeField(db_column='Data')),
            ],
            options={
                'db_table': 'funcionario_notificacao',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='funcnotificarec',
            name='funcionarioid',
        ),
        migrations.RemoveField(
            model_name='notificacaorestaurante',
            name='notificacaoid',
        ),
        migrations.DeleteModel(
            name='FuncNotficaEnv',
        ),
        migrations.DeleteModel(
            name='FuncNotificaRec',
        ),
        migrations.DeleteModel(
            name='NotificacaoRestaurante',
        ),
    ]
