# Generated by Django 4.0.3 on 2022-05-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0004_notificacaorestaurante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Codigos_postais_parcial',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('cod_distrito', models.IntegerField(db_column='cod_distrito')),
                ('cod_concelho', models.IntegerField(db_column='cod_concelho')),
                ('nome_localidade', models.CharField(blank=True, db_column='nome_localidade', max_length=50, null=True)),
                ('num_cod_postal', models.IntegerField(db_column='num_cod_postal')),
                ('ext_cod_postal', models.IntegerField(db_column='ext_cod_postal')),
                ('desig_postal', models.CharField(blank=True, db_column='desig_postal', max_length=50, null=True)),
            ],
            options={
                'db_table': 'codigos_postais_parcial',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Concelhos',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('cod_distrito', models.IntegerField(db_column='cod_distrito')),
                ('cod_concelho', models.IntegerField(db_column='cod_concelho')),
                ('nome_concelho', models.CharField(blank=True, db_column='nome_concelho', max_length=50, null=True)),
            ],
            options={
                'db_table': 'concelhos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Distritos',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('cod_distrito', models.IntegerField(db_column='cod_distrito')),
                ('nome_distrito', models.CharField(blank=True, db_column='nome_distrito', max_length=50, null=True)),
            ],
            options={
                'db_table': 'distritos',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
